### ISSUE TITLE
play_mt: more command line examples

### ISSUE THREAD

**Issue by weegreenblobbie** [mesilliac/tplay#1]
Hi, I'm trying to execute play_mt.py from the command line and I was wondering if someone could show what the values for melody and timing should be.

Thanks!

**Comment by weegreenblobbie** [comment]
Nevermind, I found the readme!

**Comment by mesilliac** [comment]
I'm not sure if i ever documented it properly, but there are a few examples included in the file itself.

It's been a while since i updated this project, so let me know if there are any issues :).

**Comment by weegreenblobbie** [comment]
If you document the options, I'm willing to port "parse_argv" to use the Python argparse library, which will create a -h --help option as well.  :) Nick

**Comment by mesilliac** [comment]
Sorry i never managed to reply to this - been super busy. Actually i don't remember what the options do ><. I meant to look into it again but haven't had the time.

Anyway, if you want, you're welcome to adapt as you see fit. This was a pretty cool project but i probably won't be able to come back to it for a while.
